configuration:
  # 界限上下文名称
  boundedContextName: "Dddml.WMs"
  # 默认模块的名称
  defaultModule: "Dddml.Wms"
  serviceName: "dapr-ddd-demo"
  # 上下文中每个实体都需要的保留属性
  defaultReservedProperties:
    aggregate:
      IsDelete:
        type: bool
    entity:
      IsDelete:
        type: bool
    view:
      TenantId:
        type: string
      CreatedById:
        type: string
      CreatedByName:
        type: string
      CreatedAt:
        type: dateTime
      UpdateById:
        type: string
      UpdateByName:
        type: string
      UpdateAt:
        type: dateTime
      IsDelete:
        type: bool
  # DDDML规范中没有明确定义的扩展点， 其值类型为Map<String, Object>
  metadata:
    HttpServicesAuthorizationEnalbled: false
    SpringSecurityEnalbeld: true
  c#:
    namespace: "com.liuxu6825.dapr-ddd-demo"
  java:
    namespace: "com.liuxu6825.dapr-ddd-demo"
  go:
    namespace: "gitee.com/liuxu6825/dapr-ddd-demo"

