configuration:
  # 界限上下文名称
  boundedContextName: "Dddml.WMs"
  # 默认模块的名称
  defaultModule: "Dddml.Wms"
  # 服务名
  serviceName: "dapr-ddd-demo"
  # 命名空间
  namespace:
    go: "gitee.com/liuxu6825/dapr-ddd-demo"
    c#: "com.liuxu6825.dapr-ddd-demo"
    java: "com.liuxu6825.dapr-ddd-demo"

  # 上下文中每个实体都需要的保留属性
  defaultReservedProperties:
    aggregate:
      IsDeleted:
        type: bool
    entity:
      IsDeleted:
        type: bool
    view:
      TenantId:
        type: string
      CreatedId:
        type: string
      CreatedName:
        type: string
      CreatedTime:
        type: dateTime
      UpdatedId:
        type: string
      UpdatedName:
        type: string
      UpdatedTime:
        type: dateTime
      DeletedId:
        type: string
      DeletedName:
        type: string
      DeletedTime:
        type: dateTime
      IsDeleted:
        type: bool
  # DDDML规范中没有明确定义的扩展点， 其值类型为Map<String, Object>
  metadata:
    HttpServicesAuthorizationEnalbled: false
    SpringSecurityEnalbeld: true
  c#:
    namespace: "com.liuxu6825.dapr-ddd-demo"
  java:
    namespace: "com.liuxu6825.dapr-ddd-demo"
  go:
    namespace: "gitee.com/liuxu6825/dapr-ddd-demo"

