configuration:
  # 界限上下文名称
  boundedContextName: "Dddml.WMs"
  # 默认模块的名称
  defaultModule: "Dddml.Wms"
  # 服务名
  serviceName: "dapr-ddd-demo"
  # API版本号
  apiVersion: "v1.0"
  # 命名空间
  namespace:
    go: "gitee.com/liuxu6825/dapr-ddd-demo"
    c#: "com.liuxu6825.dapr-ddd-demo"
    java: "com.liuxu6825.dapr-ddd-demo"
  k8s:
    namespace: "dapr-ddd-demo"
    commandImage: "192.168.64.12/dapr-ddd-demo-cmd-service:dapr-linux-arm64"
    queryImage: "192.168.64.12/dapr-ddd-demo-query-service:dapr-linux-arm64"

  # 上下文中每个实体都需要的保留属性
  defaultReservedProperties:
    aggregate:
      Id:
        type: string
        description: "ID"
      TenantId:
        type: string
        description: "租户ID"
      IsDeleted:
        type: bool
        description: "是否删除"
    entity:
      Id:
        type: string
        description: "ID"
      IsDeleted:
        type: bool
        description: "是否删除"
    view:
      TenantId:
        type: string
        description: "租户ID"
      CreatedId:
        type: string
        description: "创建人ID"
      CreatedName:
        type: string
        description: "创建人名称"
      CreatedTime:
        type: dateTime
        description: "创建时间"
      UpdatedId:
        type: string
        description: "更新人ID"
      UpdatedName:
        type: string
        description: "更新人名称"
      UpdatedTime:
        type: dateTime
        description: "更新时间"
      DeletedId:
        type: string
        description: "删除人ID"
      DeletedName:
        type: string
        description: "删除人名称"
      DeletedTime:
        type: dateTime
        description: "删除时间"
      IsDeleted:
        type: bool
        description: "是否删除"
    field:
      Id:
        type: string
        description: "ID"
      TenantId:
        type: string
        description: "租户ID"

  # DDDML规范中没有明确定义的扩展点， 其值类型为Map<String, Object>
  metadata:
    HttpServicesAuthorizationEnalbled: false
    SpringSecurityEnalbeld: true
  c#:
  java:
  go:
      DaprSrcPath: "/Users/lxd/go/src/github.com/dapr"


